name: Deploy with Kusion
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      service_name:
        required: true
        description: The name of the new service
        type: string

      resource_group:
        required: true
        description: The name of the new resource group
        type: string
      
jobs:
  scaffold-service:
    env:
      ORG_NAME: kevinz
    runs-on: ubuntu-latest
    steps:
          
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          # Repository Owner
          owner: radius-project
          # Repository name
          repository: samples
          # PAT with repository scope (https://github.com/settings/tokens)
          branch:
            v0.37
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Access cloned repository content
        run: |
          cd samples
          cd samples/demo
          ls -la
          mkdir $HOME/.kube
      - name: KUBECONFIG for Service Account (SA)
      # You may pin to the exact commit or the version.
      # uses: vbem/kubeconfig4sa@f3068dc83ba7f621a136d77e071a7bcf6f818db7
        uses: vbem/kubeconfig4sa@v1.0.4
        with:
          # K8s cluster API server URL
          server: https://34.172.248.202:37947
          # K8s cluster Certificate Authority data base64
          ca-base64: ${{ secrets.K8S_CA_BASE64 }}
          # K8s cluster name in kubeconfig file
          cluster: # optional, default is 
          # Service Account bearer token
          token: ${{ secrets.K8S_SA_TOKEN }}
          # Service Account name in kubeconfig file
          sa: deployer
          # Context name in kubeconfig file
          context: # optional, default is 
          # Context namespace in kubeconfig file
          namespace: default
          # Set as current-context in kubeconfig file
          current: # optional, default is true
          # Path of kubeconfig file
          kubeconfig: 
          # Set the KUBECONFIG environment variable available to subsequent steps
          export: true
          # Show client and server version information for the current context
          version: # optional, default is true

          #sed -i '/certificate-authority-data/d' /home/runner/work/_temp/deployer@34.172.248.202.kubeconfig
          #sed -i '/server:.*34\.172\.248\.202/ a\    insecure-skip-tls-verify: true' /home/runner/work/_temp/deployer@34.172.248.202.kubeconfig

      - name: Ensure kubeconfig in place
        run: | 
          ls /home/runner/work/_temp/deployer@34.172.248.202.kubeconfig 
          mkdir -p /home/runner/.kube
          kubectl config use-context deployer@34.172.248.202
          cp /home/runner/work/_temp/deployer@34.172.248.202.kubeconfig /home/runner/.kube/config
          cat /home/runner/.kube/config


      - name: Export kube env
        run: |
          export KUBE_CONFIG_PATH=/home/runner/.kube/config
          kubectl config current-context
          cat /home/runner/.kube/config
          kubectl get deployments -n radius-system

        
      - name: Setup radius binary
        uses: plinioh/setup-binary-action@v1.0.0
        with:
          binaryName: rad
          binaryUrl: https://github.com/kevinz/gh_workflow/releases/download/0.01/radius.tar.gz
          binaryPathInArchive: rad_linux_amd64


      - name: Radius deployment
        run: |
          rad bicep download 
          cd samples/samples/demo
          rad workspace create kubernetes default
          rad workspace switch default
          rad group create ${{ inputs.resource_group }}
          rad group switch ${{ inputs.resource_group }}
          rad env create default 
          rad env switch default
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/sqldatabases:latest  --resource-type Applications.Datastores/sqlDatabases
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/rabbitmqqueues:latest  --resource-type Applications.Messaging/rabbitMQQueues
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/secretstores:latest  --resource-type Applications.Dapr/secretStores
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/statestores:latest  --resource-type Applications.Dapr/stateStores
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/mongodatabases:latest --resource-type Applications.Datastores/mongoDatabases
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/rediscaches:latest --resource-type Applications.Datastores/redisCaches
          rad recipe register  default --template-kind bicep --template-path ghcr.io/radius-project/recipes/local-dev/pubsubbrokers:latest  --resource-type Applications.Dapr/pubSubBrokers
          rad deploy app.bicep -a ${{ inputs.service_name }} -g ${{ inputs.resource_group }} -e default


                
