apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - image: messenger_v2
          name: messenger
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
