name: Scaffold a new service
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      service_name:
        required: true
        description: The name of the new service
        type: string
jobs:
  scaffold-service:
    env:
      ORG_NAME: kevinz
    runs-on: ubuntu-latest
    steps:
      - uses: port-labs/cookiecutter-gha@v1.1.1
        id: scaff
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_context).runId }}
          repositoryName: ${{ inputs.service_name }}
          portUserInputs: '{"cookiecutter_app_name": "${{ inputs.service_name }}" }'
          cookiecutterTemplate: https://github.com/lacion/cookiecutter-golang
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
          
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          # Repository Owner
          owner: radius-project
          # Repository name
          repository: samples
          # PAT with repository scope (https://github.com/settings/tokens)
          branch:
            v0.37
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }}


      - name: kubectl-simple
        # You may pin to the exact commit or the version.
        # uses: steebchen/kubectl@7c4c70d551952e40881998b840e16d4d9824a54f
        uses: steebchen/kubectl@v2.1.1
        with:
          # kubectl version, e.g. `v1.21.0`, defaults to latest
          version: # optional, default is latest
          # kube config data
          config: |
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTWpVMU9UQTRNalV3SGhjTk1qUXdPVEEyTURJME56QTFXaGNOTXpRd09UQTBNREkwTnpBMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTWpVMU9UQTRNalV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ21DTlNpbDRmQUdxUjRrSStaT2kxY0M2eUd3TllYNTZLMDZCcXNERG8KV1BUeXhFTGRJV2FYRUEvYU9NcjhKQzVzN2VqclMvSUljRUJtaGFsODZlREVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXNRSkJsNGZ2bUlDK1Zkc0VsQS9WCkdkdGFVRHd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTG0wTUJTUk5Fd2FNSXcvSkJQTVFyeUxabnJLMFJsRmMKMkZjRkhCZURHVGtDSUVhWGl4MkZ5eFhyZ1l5d0xtOWxKekU2K3IwazRsRHQxSW9DRUd0NlN2a1kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
                server: https://34.172.248.202:37757
              name: k3d-k3s-default
            contexts:
            - context:
                cluster: k3d-k3s-default
                user: admin@k3d-k3s-default
              name: k3d-k3s-default
            current-context: k3d-k3s-default
            kind: Config
            preferences: {}
            users:
            - name: admin@k3d-k3s-default
              user:
                client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJUEYweCtHQUE5bzh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekkxTlRrd09ESTFNQjRYRFRJME1Ea3dOakF5TkRjd05Wb1hEVEkxTURrdwpOakF5TkRjd05Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQSDU3aU1QYXIyZkN0WGgKRXBsRDNnYkZCZGVFV2lyQWRQRW5DUm8vY1NHbnFzNlY0Smhxd005VXhjaHR0Yko3TExjSTFRVnlhSTJDcGFhVAp4aE5NMnNHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXBVclFvV1Z5eVpOUlV0VTNRWG96YVRUQnRpakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBZUhkMFR3eW8xWmFPMXF6R2ZaSVNaR0NYa0pLNm5rbE9kV2c1YU0rbUpNUUloQU5FVnpUVlJqVE9haG4zdgpNNG1Yd0RHUmRYNzVndGFrak96Y2xXc1M3Y3kvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTWpVMU9UQTRNalV3SGhjTk1qUXdPVEEyTURJME56QTFXaGNOTXpRd09UQTBNREkwTnpBMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTWpVMU9UQTRNalV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRY1Z2RVNWRlVGUTNrbzcvcmhOT3NJZjJJVkRsd1ZIRExaVER3WkNzQlYKZk5TU0Q2dktSY1RJcERPcjN2cmxDVGVrVGE0MFFCejBPRjNxd1ZRS0Z1ZjdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUtWSzBLRmxjc21UVVZMVk4wRjZNCjJrMHdiWW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU03ZVMvdDNHVmpab3hSY2RpbWFOaDJRcTg2L0tmZDQKd243eGFLVFJLNEtuQWlBaEl6UExnaURySkl5R1BkN1hicnM5NWljRkdaNXVDSjFySXIrNWcvZVdpUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd3RUNMWk55UnF5NThNRmMyTktVOG81NXJSci9QajVqekRqY3lpZ1RmRDhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOGZudUl3OXF2WjhLMWVFU21VUGVCc1VGMTRSYUtzQjA4U2NKR2o5eElhZXF6cFhnbUdyQQp6MVRGeUcyMXNuc3N0d2pWQlhKb2pZS2xwcFBHRTB6YXdRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
              
          # kubectl command to run, without the kubectl, e.g. `get pods`
          command: get pods --all-namespaces
          # Url to download the binaries from, defaults to the official dl.k8s.io url
          binaries-url: # optional
                   
                    
                              
      
                
