name: Scaffold a new service
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      service_name:
        required: true
        description: The name of the new service
        type: string
jobs:
  scaffold-service:
    env:
      ORG_NAME: kevinz
    runs-on: ubuntu-latest
    steps:
      - uses: port-labs/cookiecutter-gha@v1.1.1
        id: scaff
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_context).runId }}
          repositoryName: ${{ inputs.service_name }}
          portUserInputs: '{"cookiecutter_app_name": "${{ inputs.service_name }}" }'
          cookiecutterTemplate: https://github.com/lacion/cookiecutter-golang
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
          
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          # Repository Owner
          owner: radius-project
          # Repository name
          repository: samples
          # PAT with repository scope (https://github.com/settings/tokens)
          branch:
            v0.37
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Access cloned repository content
        run: |
          cd samples
          cd samples/demo
          ls -la


      - name: Create kube context file
        uses: 1arp/create-a-file-action@0.4.5
        with:
          # Path from cwd where file is to be created
          path: # default is 
            $HOME/.kube/
          # If the path provided is an absolute path
          file: config
          # The content of the file
          content: ${{ secrets.KUBE_CONFIG_DATA }}
          
      - name: list kube config
        run: |
          ls -la $HOME/.kube/
          
      - name: kubectl-simple
        # You may pin to the exact commit or the version.
        # uses: steebchen/kubectl@7c4c70d551952e40881998b840e16d4d9824a54f
        uses: steebchen/kubectl@v2.1.1
        with:

          # kube config data
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          # kubectl command to run, without the kubectl, e.g. `get pods`
          command: config view
          # Url to download the binaries from, defaults to the official dl.k8s.io url                   
                    
                              
      
                
